### ISSUE TITLE
Account Manager Onboarding Checklist 

### ISSUE THREAD

**Issue by BuhusLucian** [twisterdotcom/docsTest#4]
### SRAM(s) Email(s)

- lucian.buhus@team.expensify.com
- lucian.buhus@partnerhero.com

### Are they a Team Lead or Agent?

Agent

### SRAM Timezone and shift:

Eastern European Time (EET; UTC+02:00) Monday to Friday

### Coach Tasks:

- [X] Request that the SR be added as a member to "#sr-account-managers" Slack workspace, by clicking on "Expensify" (top left in Slack) > "Invite People To Expensify."
- [X] Assign customers to SRAM
- [X] Assign a Coach Mentor to the SRAM using [these instructions](https://stackoverflowteams.com/c/expensify/questions/15287/15288#15288)
- [X] Once Coach Tasks are complete, assign the Coach Mentor to complete the below mentor tasks

### Coach Mentor Tasks:

- [X] Review this [SO](https://stackoverflow.com/c/expensify/questions/14477) on mentoring best practices
- [X] Share this set of Account Managers [SOs](https://stackoverflowteams.com/c/expensify/posts/tagged/882) with SRAM and ask them to review them
- [X] Reach out directly to your mentee in Slack (via DM) to introduce yourself
- [X] Ask your mentee to enter their GH handle (without the @) in Concierge (Concierge > Settings > [GitHub Details](https://www.expensify.com/concierge/#/settings/gitHubDetails) > Save)
- [X] Add them to the [#account-management](https://app.slack.com/client/T03SC9DTT/C03GV4V2KCM) channel in Slack
- [X] Confirm they have users assigned to them in Concierge
- [X] Book an initial sync with them to introduce yourself
