### ISSUE TITLE
Account Manager Offboarding Checklist

### ISSUE THREAD

**Issue by BuhusLucian** [twisterdotcom/docsTest#5]
### SRAM(s) Email(s)

- lucian.buhus@team.expensify.com
- lucian.buhus@partnerhero.com

### Infra Tasks:

- [X] Remove the SR from the [SR Account Managers](https://github.com/orgs/Expensify/teams/sr-account-managers/members) team in the Expensify/Expensify repo.
- [X] Remove the SR from the "#sr-account-managers" Slack workspace.

### Coach Tasks:

- [X] Remove the SR from the "accountManager" beta in Supportal.
- [X] Post in the "#vip_managed1000" Slack channel and await further instructions on unassigning the SR's Admins/customers.
